# Generated by Django 3.1.5 on 2021-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=30)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
            ],
        ),
    ]
