# Generated by Django 3.1.5 on 2021-03-15 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210315_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporttype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sporttype',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
